import { Post, User } from "@/types";

// dummyUsers (unchanged)
export const dummyUsers: User[] = [
  {
    id: "1",
    username: "johnDoe",
    name: "John Doe",
    image: "https://picsum.photos/200/300",
    bio: "Software engineer by day, gamer by night",
  },
  {
    id: "2",
    username: "janeDoe",
    name: "Jane Doe",
    image: "https://picsum.photos/200/301",
    bio: "Designer and artist, loves hiking and photography",
  },
  {
    id: "3",
    username: "bobSmith",
    name: "Bob Smith",
    image: "https://picsum.photos/200/302",
    bio: "Musician and writer, loves playing guitar and reading",
  },
  {
    id: "4",
    username: "aliceJohnson",
    name: "Alice Johnson",
    image: "https://picsum.photos/200/303",
    bio: "Student and activist, passionate about social justice",
  },
  {
    id: "5",
    username: "mikeWilliams",
    name: "Mike Williams",
    image: "https://picsum.photos/200/304",
    bio: "Entrepreneur and investor, loves playing sports and traveling",
  },
];

// Declare dummyPosts without parent references initially
export const dummyPosts: Post[] = [
  {
    id: "1",
    title: "Hello World!",
    content: "This is my first post!",
    createdAt: "2023-02-20T14:30:00.000Z",
    user_id: "1",
    user: dummyUsers[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "2",
    title: "My favorite book",
    content: "I just finished reading 'To Kill a Mockingbird' and it's amazing!",
    createdAt: "2023-02-21T10:00:00.000Z",
    user_id: "2",
    user: dummyUsers[1],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "3",
    title: "New music alert!",
    content: "Just released a new single, check it out!",
    createdAt: "2023-02-22T12:00:00.000Z",
    user_id: "3",
    user: dummyUsers[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "4",
    title: "Hiking trip",
    content: "Just got back from an amazing hiking trip in the mountains",
    createdAt: "2023-02-23T16:00:00.000Z",
    user_id: "1",
    user: dummyUsers[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "5",
    title: "Favorite food",
    content: "What's your favorite food?",
    createdAt: "2023-02-24T10:00:00.000Z",
    user_id: "4",
    user: dummyUsers[3],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "6",
    title: "Reply to post 1",
    content: "Love your first post!",
    createdAt: "2023-02-20T15:00:00.000Z",
    user_id: "2",
    user: dummyUsers[1],
    parent_id: "1",
    parent: null,
    replies: [],
  },
  {
    id: "7",
    title: "Reply to post 2",
    content: "I loved that book too!",
    createdAt: "2023-02-21T11:00:00.000Z",
    user_id: "3",
    user: dummyUsers[2],
    parent_id: "2",
    parent: null,
    replies: [],
  },
  {
    id: "8",
    title: "New project",
    content: "Just started working on a new project, excited to share it soon!",
    createdAt: "2023-02-25T14:00:00.000Z",
    user_id: "5",
    user: dummyUsers[4],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "9",
    title: "Travel plans",
    content: "Anyone have any travel plans for the summer?",
    createdAt: "2023-02-26T10:00:00.000Z",
    user_id: "1",
    user: dummyUsers[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "10",
    title: "Photography tips",
    content: "Sharing some tips for better landscape photography!",
    createdAt: "2023-02-27T09:00:00.000Z",
    user_id: "2",
    user: dummyUsers[1],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "11",
    title: "Reply to post 5",
    content: "Pizza is my go-to food!",
    createdAt: "2023-02-24T11:30:00.000Z",
    user_id: "5",
    user: dummyUsers[4],
    parent_id: "5",
    parent: null,
    replies: [],
  },
  {
    id: "12",
    title: "New guitar",
    content: "Just got a new acoustic guitar, can't wait to play it!",
    createdAt: "2023-02-28T13:00:00.000Z",
    user_id: "3",
    user: dummyUsers[2],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "13",
    title: "Reply to post 9",
    content: "Planning to visit Japan this summer, any tips?",
    createdAt: "2023-02-26T12:00:00.000Z",
    user_id: "4",
    user: dummyUsers[3],
    parent_id: "9",
    parent: null,
    replies: [],
  },
  {
    id: "14",
    title: "Tech conference",
    content: "Attending a tech conference next week, anyone else going?",
    createdAt: "2023-03-01T15:00:00.000Z",
    user_id: "1",
    user: dummyUsers[0],
    parent_id: null,
    parent: null,
    replies: [],
  },
  {
    id: "15",
    title: "Reply to post 10",
    content: "Great tips! What's your favorite camera for landscapes?",
    createdAt: "2023-02-27T10:30:00.000Z",
    user_id: "3",
    user: dummyUsers[2],
    parent_id: "10",
    parent: null,
    replies: [],
  },
];

// Set parent references and replies hierarchy after declaration
dummyPosts.forEach((post) => {
  if (post.parent_id) {
    const parentPost = dummyPosts.find((p) => p.id === post.parent_id);
    if (parentPost) {
      post.parent = parentPost;
      parentPost.replies.push(post);
    }
  }
});